from unittest import TestCase
from data_structures.linked_lists.singularly_linked_list.singularly_linked_list import SingularlyLinkedList
from data_structures.solutions.linked_lists.singularly_linked_list.singularly_linked_list import SingularlyLinkedList as SingularlyLinkedListSolution

class TestSingularlyLinkedList(TestCase):
    pass
